base_url = "https://quasar-sar.ru"

title = "«Квазар»"
description = "Малогабаритная радиолокационная станция с синтезированной апертурой для беспилотных летательных аппаратов"

compile_sass = true
build_search_index = true
default_language = "ru"

[markdown]
smart_punctuation = true
github_alerts = true

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
email = "kernel386@mail.ru"
github_username = "quasar-project"

[languages.en]
title = "QuaSAR"
description = "Compact synthetic aperture radar station for UAVs"
