base_url = "https://whs31.com"

title = "QuaSAR"
description = "Программный комплекс формирования радиолокационных изображений с синтезированной апертурой"

compile_sass = true
build_search_index = true
default_language = "ru"

[markdown]
smart_punctuation = true
github_alerts = true

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
username = "Квазар"
user_title = "Малогабаритная радиолокационная станция с синтезированной апертурой"
email = "kernel386@mail.ru"
github_username = "quasar-project"

[languages.en]
title = "QuaSAR"
description = "Synthetic Aperture Radar Imaging Software Package"
